---
title: "Covid91 vaccine study Final2025"
author: "Issa Darrouj"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`" 
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
FinalDat <-read.csv(file="finalSumr2024.csv",header=TRUE)
#recode to remove the annoying "X" from the dataframe
FinalData <- FinalDat  %>% select(-one_of("X"))
FinalData <- FinalData %>%
mutate(across(where(is.character), as.factor))
FinalData$treatment <- relevel(FinalData$treatment,ref="placebo")
#FinalData$infected <- relevel(FinalData$infected,ref="OK")
M = filter(FinalData, sex =="M")
F = filter(FinalData, sex =="F")
gay = filter(FinalData, LGBTQ =="gay")
Druguser = filter(FinalData, DrugUser =="yes")
```

# Coding details

Separating the variables into the four groups they belonged to was crucial for an effective evaluation of the data. "M", "F", "gay", and "drug users" are the four variables I created. To determine whether or not they should get the Covid-19 vaccine, they were kept apart. I did this in order to generate the efficacy intervals. They were kept in different variables. 

# Introduction

A new  preventative vaccine (covid921) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of subpopulations tracked. Consider population subgroups by gender( guys and gals), drug use, and sexual orientation. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.

## Males


## Females


## LGBTQ



## Druggies


# Overall Results and Conclusions